import { useEffect, useMemo, useRef, useState } from 'react';
import { DecisionLab, useDecisionLab } from '../components/DecisionLab';

type Cell = { open: boolean; flag: boolean; mine: boolean; n: number };
type Constraint = { cells: string[]; mines: number };
type BoardState = { size: number; mines: number; visible: string[]; covered: string[]; frontier: string[]; safeReveals: string[]; suspectedMines: string[]; riskCandidates: Array<{ key: string; risk: number }>; actions: string[]; moves: number };
const SIZE = 14; const MINES = 20;
const DIRECTIONS = [-1, 0, 1].flatMap(row => [-1, 0, 1].map(col => [row, col] as const)).filter(([row, col]) => row || col);
const key = (row: number, col: number) => `${row},${col}`;
const neighbours = (row: number, col: number) => DIRECTIONS.map(([dr, dc]) => [row + dr, col + dc] as const).filter(([r, c]) => r >= 0 && r < SIZE && c >= 0 && c < SIZE);
const emptyBoard = (): Cell[] => Array.from({ length: SIZE * SIZE }, () => ({ open: false, flag: false, mine: false, n: 0 }));

function deductions(cells: Cell[]) {
  const constraints: Constraint[] = []; const frontier = new Set<string>(); const risk = new Map<string, number>();
  cells.forEach((cell, index) => {
    const row = Math.floor(index / SIZE); const col = index % SIZE;
    if (cell.open) neighbours(row, col).forEach(([r, c]) => { if (!cells[r * SIZE + c].open && !cells[r * SIZE + c].flag) frontier.add(key(r, c)); });
    if (!cell.open || cell.n === 0) return;
    const adjacent = neighbours(row, col); const flagged = adjacent.filter(([r, c]) => cells[r * SIZE + c].flag).length;
    const hidden = adjacent.filter(([r, c]) => !cells[r * SIZE + c].open && !cells[r * SIZE + c].flag).map(([r, c]) => key(r, c));
    if (!hidden.length) return;
    const remaining = Math.max(0, cell.n - flagged); constraints.push({ cells: hidden, mines: remaining });
    const localRisk = remaining / hidden.length; hidden.forEach(value => risk.set(value, (risk.get(value) ?? 0) + localRisk));
  });
  const safe = new Set<string>(); const suspected = new Set<string>();
  constraints.forEach(item => { if (item.mines === 0) item.cells.forEach(value => safe.add(value)); if (item.mines === item.cells.length) item.cells.forEach(value => suspected.add(value)); });
  for (const first of constraints) for (const second of constraints) {
    if (first === second || first.cells.length >= second.cells.length || !first.cells.every(value => second.cells.includes(value))) continue;
    const difference = second.cells.filter(value => !first.cells.includes(value)); const mineDifference = second.mines - first.mines;
    if (mineDifference === 0) difference.forEach(value => safe.add(value));
    if (mineDifference === difference.length) difference.forEach(value => suspected.add(value));
  }
  const covered = cells.flatMap((cell, index) => cell.open || cell.flag ? [] : [key(Math.floor(index / SIZE), index % SIZE)]);
  const riskCandidates = [...frontier].map(value => ({ key: value, risk: risk.get(value) ?? MINES / Math.max(1, covered.length) })).sort((a, b) => a.risk - b.risk).slice(0, 12);
  return { safe, suspected, frontier: [...frontier], riskCandidates, covered };
}

function makeState(cells: Cell[], moves: number): BoardState {
  const result = deductions(cells); const visible = cells.map(cell => cell.open ? String(cell.n) : cell.flag ? 'F' : '#'); const actions: string[] = [];
  const add = (kind: string, value: string) => { const [row, col] = value.split(','); actions.push(`${kind}_${row}_${col}`); };
  if (result.suspected.size) [...result.suspected].slice(0, 12).forEach(value => add('flag', value));
  else if (result.safe.size) [...result.safe].forEach(value => add('reveal', value));
  else if (result.riskCandidates.length) result.riskCandidates.forEach(item => add('reveal', item.key));
  else result.covered.slice(0, 12).forEach(value => add('reveal', value));
  return { size: SIZE, mines: MINES, visible, covered: result.covered, frontier: result.frontier, safeReveals: [...result.safe], suspectedMines: [...result.suspected], riskCandidates: result.riskCandidates, actions: actions.slice(0, 24), moves };
}

export default function MinesweeperGamePage() {
  const lab = useDecisionLab(); const epoch = useRef(0);
  const [cells, setCells] = useState<Cell[]>(emptyBoard); const [generated, setGenerated] = useState(false); const [running, setRunning] = useState(false); const [paused, setPaused] = useState(false); const [autopilot, setAutopilot] = useState(false); const [thinking, setThinking] = useState(false); const [moves, setMoves] = useState(0); const [message, setMessage] = useState('点击格子开始，也可以交给 Jev 自动扫雷。'); const [confidence, setConfidence] = useState('待接管'); const [logs, setLogs] = useState<string[]>([]); const [trace, setTrace] = useState<unknown[]>([]);
  const generate = (first: number, board: Cell[]) => { const row = Math.floor(first / SIZE); const col = first % SIZE; const banned = new Set([key(row, col), ...neighbours(row, col).map(([r, c]) => key(r, c))]); const candidates = board.map((_, index) => key(Math.floor(index / SIZE), index % SIZE)).filter(value => !banned.has(value)).sort(() => Math.random() - .5); candidates.slice(0, MINES).forEach(value => { const [r, c] = value.split(',').map(Number); board[r * SIZE + c].mine = true; }); board.forEach((cell, index) => { const row = Math.floor(index / SIZE); const col = index % SIZE; cell.n = neighbours(row, col).filter(([r, c]) => board[r * SIZE + c].mine).length; }); return board; };
  const record = (event: unknown) => setTrace(previous => { const next = [...previous, event]; fetch('/minesweeper-api/trace', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(next) }).catch(() => {}); localStorage.setItem('react-minesweeper-trace', JSON.stringify(next)); return next; });
  const reveal = (index: number) => { setCells(previous => { let board = previous.map(cell => ({ ...cell })); if (!generated) { board = generate(index, board); setGenerated(true); } const target = board[index]; if (target.open || target.flag) return board; if (target.mine) { target.open = true; setRunning(false); setAutopilot(false); setMessage('踩到雷了，这一局结束。让 Jev 再试一次。'); return board; } const queue = [index]; const seen = new Set<number>(); while (queue.length) { const current = queue.shift()!; if (seen.has(current)) continue; seen.add(current); const cell = board[current]; if (cell.open || cell.flag || cell.mine) continue; cell.open = true; if (cell.n === 0) { const row = Math.floor(current / SIZE); const col = current % SIZE; neighbours(row, col).forEach(([r, c]) => queue.push(r * SIZE + c)); } } setMoves(value => value + 1); if (board.filter(cell => cell.open && !cell.mine).length === SIZE * SIZE - MINES) { setRunning(false); setAutopilot(false); setMessage('Jev 清空了所有安全格，扫雷成功。'); } return board; }); };
  const toggleFlag = (index: number) => { setMoves(value => value + 1); setCells(previous => previous.map((cell, current) => current === index && !cell.open ? { ...cell, flag: !cell.flag } : cell)); };
  useEffect(() => { if (!autopilot || paused) return; const timer = window.setInterval(async () => { if (thinking) return; setThinking(true); const currentEpoch = epoch.current; const state = makeState(cells, moves); try { const data = await lab.request('/minesweeper-api/move', state); if (currentEpoch !== epoch.current || !autopilot) return; const original = data?.answers?.action?.choice as string; if (!state.actions.includes(original)) throw new Error('Jev 返回了当前候选列表之外的动作'); let choice = original; const revealActions = state.actions.filter(action => action.startsWith('reveal_')); if (choice.startsWith('reveal_') && revealActions.length) { const risk = data?.answers?.[`mine_${choice.split('_')[1]}_${choice.split('_')[2]}`]?.noul ?? 1; if (risk >= 0.35 || (data?.answers?.action?.confidence ?? 0) < 0.7) choice = revealActions.map(action => ({ action, risk: data?.answers?.[`mine_${action.split('_')[1]}_${action.split('_')[2]}`]?.noul ?? 1 })).sort((a, b) => a.risk - b.risk)[0].action; } if (!state.actions.includes(choice)) throw new Error('安全筛选后动作不在候选列表中'); lab.executed(choice, original); const match = choice.match(/^(reveal|flag)_(\d+)_(\d+)$/); if (!match) throw new Error('Jev 返回了无法执行的动作'); const row = Number(match[2]); const col = Number(match[3]); const index = row * SIZE + col; const conf = Math.round((data?.answers?.action?.confidence ?? 0) * 100); setConfidence(`confidence ${conf}%`); const changed = choice !== original; const label = `${match[1] === 'flag' ? '插旗' : '翻开'} (${row + 1}, ${col + 1})`; setMessage(changed ? `系统将高风险选择改为${label}。` : `Jev 选择${label}。`); setLogs(previous => [`${changed ? '系统调整' : 'Jev'} ${label} · ${conf}%`, ...previous].slice(0, 6)); if (match[1] === 'flag') toggleFlag(index); else reveal(index); record({ step: trace.length + 1, state, answer: data, original, selected: choice, timestamp: new Date().toISOString() }); } catch (error) { setAutopilot(false); setRunning(false); setMessage(error instanceof Error ? error.message : 'Jev 请求失败，自动扫雷已停止。'); } finally { setThinking(false); } }, 700); return () => window.clearInterval(timer); }, [autopilot, paused, thinking, cells, moves]);
  const reset = () => { epoch.current++; lab.reset(); setCells(emptyBoard()); setGenerated(false); setRunning(false); setPaused(false); setAutopilot(false); setThinking(false); setMoves(0); setMessage('点击格子开始，也可以交给 Jev 自动扫雷。'); setConfidence('待接管'); setLogs([]); setTrace([]); localStorage.removeItem('react-minesweeper-trace'); };
  const startAuto = async () => { if (autopilot) { setAutopilot(false); setPaused(true); return; } try { const response = await fetch('/minesweeper-api/status'); if (!response.ok) throw new Error('请先配置 Jev 服务'); setRunning(true); setPaused(false); setAutopilot(true); setMessage('Jev 已接管棋盘，正在寻找第一步。'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Jev 服务不可用'); } };
  const opened = cells.filter(cell => cell.open && !cell.mine).length; const flags = cells.filter(cell => cell.flag).length; const status = autopilot ? (thinking ? 'JEV · THINKING' : 'JEV · DRIVING') : running ? (paused ? 'BOARD · PAUSED' : 'LOCAL BOARD · PLAYING') : 'LOCAL BOARD · READY'; const metrics = useMemo(() => [[moves, '动作'], [opened, '已打开'], [flags, '旗帜']], [moves, opened, flags]);
  return <section className="native-game live-lab"><div className="native-game-head"><div><p className="eyebrow">MINESWEEPER / LIVE GAME</p><h1>看 Jev 如何判断一格</h1><p>数字是线索，未知格是选择。把一次翻开或插旗，拆成可观察的决策。</p></div><span>{status}</span></div><div className="lab-strategy"><b>当前策略</b><span>优先使用数字推导出的确定安全格和确定雷格，再比较局部风险；首步保护当前点击格及周围八格。</span></div><div className="native-game-layout"><article className="native-board-card"><div className="mine-grid live-mine-grid">{cells.map((cell, index) => <button key={index} className={`mine-cell ${cell.open ? 'revealed' : 'covered'} ${cell.flag ? 'flagged' : ''} ${cell.mine && cell.open ? 'mine-hit' : ''}`} onClick={() => { if (!autopilot) { setRunning(true); reveal(index); } }} onContextMenu={event => { event.preventDefault(); if (!autopilot) toggleFlag(index); }}>{cell.open ? (cell.mine ? '✹' : cell.n || '') : cell.flag ? '⚑' : ''}</button>)}</div><div className="native-actions"><button className="primary-button" onClick={reset}>开始新局</button><button onClick={startAuto}>{autopilot ? '停止 Jev 扫雷' : 'Jev 自动扫雷'}</button><button onClick={() => { if (running) setPaused(value => !value); }}>{paused ? '继续' : '暂停'}</button></div><div className="native-hint">左键翻开 · 右键插旗 · 默认 14×14 / 20 颗雷</div></article><aside className="native-side"><DecisionLab lab={lab} game="mines" paused={paused} /><div className="native-metrics">{metrics.map(([value, label]) => <b key={label}>{String(value).padStart(2, '0')}<small>{label}</small></b>)}</div><div className="native-driver"><div className="driver-topline"><strong>Jev 扫雷员</strong><span>{confidence}</span></div><p>{message}</p><div className="native-log">{logs.map((log, index) => <div key={`${log}-${index}`}>{log}</div>)}</div></div><div className="native-rules"><b>怎么玩</b><span>普通点击　翻开格子</span><span>右键点击　插旗 / 取消</span><span>目标　打开所有非雷格</span></div></aside></div></section>;
}
