import { useEffect, useRef, useState, type CSSProperties, type RefObject } from 'react';
import type { TraceEvent } from '../lib/trace';

type Point = { x: number; y: number };
type SnakeState = { grid: number; snake: Point[]; food: Point; legalMoves?: string[]; plannedDirection?: string; loopDetected?: boolean; recentHeads?: Point[]; score?: number; direction?: Point | string };
type JevAnswer = { model?: string; answers?: { move?: { choice?: string; confidence?: number; probabilities?: Record<string, number> }; trap?: { noul?: number } } };
type SnakeEvent = TraceEvent & { state: SnakeState; answer?: JevAnswer; request?: unknown };
type TraceFile = { events: SnakeEvent[] } | SnakeEvent[];
const accents = { old: '#ff7773', shaped: '#b7ff4a' };

function eventsFrom(value: TraceFile): SnakeEvent[] { return Array.isArray(value) ? value : value.events; }
function directionName(value?: Point | string | null) { if (!value) return '—'; if (typeof value === 'string') return ({ up: '↑ 上', down: '↓ 下', left: '← 左', right: '→ 右' } as Record<string, string>)[value] ?? value; if (value.x === 1) return '→ 右'; if (value.x === -1) return '← 左'; if (value.y === 1) return '↓ 下'; return '↑ 上'; }
function distance(state: SnakeState) { return Math.abs(state.snake[0].x - state.food.x) + Math.abs(state.snake[0].y - state.food.y); }
function drawBoard(canvas: HTMLCanvasElement | null, event: SnakeEvent | undefined, accent: string) { if (!canvas || !event) return; const ctx = canvas.getContext('2d'); if (!ctx) return; const grid = event.state.grid || 20; const cell = canvas.width / grid; ctx.fillStyle = '#0d1719'; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.strokeStyle = 'rgba(106,242,210,.07)'; for (let i = 1; i < grid; i++) { ctx.beginPath(); ctx.moveTo(i * cell, 0); ctx.lineTo(i * cell, canvas.height); ctx.stroke(); ctx.beginPath(); ctx.moveTo(0, i * cell); ctx.lineTo(canvas.width, i * cell); ctx.stroke(); } ctx.fillStyle = '#ff9b64'; ctx.shadowColor = '#ff9b64'; ctx.shadowBlur = 18; ctx.beginPath(); ctx.arc(event.state.food.x * cell + cell / 2, event.state.food.y * cell + cell / 2, cell * .28, 0, Math.PI * 2); ctx.fill(); ctx.shadowBlur = 0; event.state.snake.forEach((part, index) => { ctx.fillStyle = index === 0 ? accent : '#5d9e54'; ctx.globalAlpha = 1 - index * .1; ctx.beginPath(); ctx.roundRect(part.x * cell + 3, part.y * cell + 3, cell - 6, cell - 6, 5); ctx.fill(); }); ctx.globalAlpha = 1; }

export default function SnakeComparePage() {
  const [oldTrace, setOldTrace] = useState<SnakeEvent[]>([]); const [newTrace, setNewTrace] = useState<SnakeEvent[]>([]); const [step, setStep] = useState(0); const [playing, setPlaying] = useState(false); const oldCanvas = useRef<HTMLCanvasElement>(null); const newCanvas = useRef<HTMLCanvasElement>(null);
  useEffect(() => { Promise.all([fetch('/traces/snake-baseline-live.json').then(response => response.json()), fetch('/traces/snake-live.json').then(response => response.json())]).then(([oldData, newData]) => { setOldTrace(eventsFrom(oldData)); setNewTrace(eventsFrom(newData)); }); }, []);
  const total = Math.min(oldTrace.length, newTrace.length); const index = total ? Math.min(step, total - 1) : 0; const oldEvent = oldTrace[index]; const newEvent = newTrace[index];
  useEffect(() => { drawBoard(oldCanvas.current, oldEvent, accents.old); drawBoard(newCanvas.current, newEvent, accents.shaped); }, [oldEvent, newEvent]);
  useEffect(() => { if (!playing || !total) return; const timer = window.setInterval(() => setStep(value => value >= total - 1 ? (setPlaying(false), value) : value + 1), 650); return () => window.clearInterval(timer); }, [playing, total]);
  return <section className="react-compare"><div className="compare-head"><div><p className="eyebrow">REACT TRACE VIEWER / SNAKE</p><h1>同一条蛇，两种交互</h1><p>先看本轮输入，再看 Jev 的选择，最后核对实际执行动作。</p></div><span className="compare-status">{total ? (playing ? '两边同步播放' : '可以逐步查看') : '正在加载记录'}</span></div><div className="compare-toolbar"><button className="primary-button" onClick={() => setPlaying(value => !value)}>{playing ? '暂停' : '播放'}</button><button onClick={() => setStep(value => Math.max(0, value - 1))}>←</button><button onClick={() => setStep(value => Math.min(Math.max(0, total - 1), value + 1))}>→</button><button onClick={() => { setPlaying(false); setStep(0); }}>重置</button><span>STEP {String(index + 1).padStart(2, '0')} / {String(total).padStart(2, '0')}</span></div><div className="react-boards"><SnakeCard title="原始 Jev" subtitle="只传当前棋盘" accent={accents.old} canvasRef={oldCanvas} event={oldEvent} /><SnakeCard title="约束后 Jev" subtitle="状态 + 反馈" accent={accents.shaped} canvasRef={newCanvas} event={newEvent} /></div></section>;
}

function SnakeCard({ title, subtitle, accent, canvasRef, event }: { title: string; subtitle: string; accent: string; canvasRef: RefObject<HTMLCanvasElement | null>; event?: SnakeEvent }) {
  const move = event?.answer?.answers?.move; const probabilities = move?.probabilities ? Object.entries(move.probabilities).sort((a, b) => b[1] - a[1]) : []; const selected = event?.selected ?? move?.choice; const adjusted = !!event?.selected && !!move?.choice && event.selected !== move.choice;
  return <article className="react-board-card" style={{ '--accent': accent } as CSSProperties}><div className="react-card-head"><div><h2>{title}</h2><p>{subtitle}</p></div><span>RECORDED</span></div><canvas ref={canvasRef} width={560} height={560} /><div className="react-metrics"><b>{String(event?.scoreAfter ?? event?.state.score ?? 0).padStart(2, '0')}<small>得分</small></b><b>{String(event?.state.snake.length ?? 0).padStart(2, '0')}<small>长度</small></b><b>{String(event?.step ?? 0).padStart(2, '0')}<small>动作</small></b></div><div className="react-decision"><strong>实际执行：{directionName(selected)}</strong><p>{adjusted ? `Jev 原始选择 ${directionName(move?.choice)}，系统改为 ${directionName(event?.selected)}。` : `Jev 选择 ${directionName(selected)}，置信度 ${Math.round((move?.confidence ?? 0) * 100)}%。`}</p></div>{event && <div className="decision-inspector"><div className="inspector-block inspector-input"><div className="inspector-title"><span>01 / 输入给 Jev</span><b>棋盘状态</b></div><div className="inspector-grid"><span>蛇头<b>{event.state.snake[0].x}, {event.state.snake[0].y}</b></span><span>食物<b>{event.state.food.x}, {event.state.food.y}</b></span><span>距离<b>{distance(event.state)} 格</b></span><span>蛇身<b>{event.state.snake.length} 格</b></span></div><div className="inspector-label">允许的方向</div><div className="inspector-chips">{(event.state.legalMoves ?? []).map(value => <i key={value}>{directionName(value)}</i>)}</div><div className="inspector-subline">路径参考：{directionName(event.state.plannedDirection)} · 近期轨迹：{event.state.recentHeads?.length ?? 0} 步 · 循环：{event.state.loopDetected ? '检测到' : '未检测到'}</div></div><div className="inspector-arrow">↓</div><div className="inspector-block inspector-output"><div className="inspector-title"><span>02 / Jev 输出</span><b>{event.answer?.model ?? 'jev'}</b></div><div className="output-choice"><span>模型选择</span><strong>{directionName(move?.choice)}</strong><em>{Math.round((move?.confidence ?? 0) * 100)}%</em></div><div className="probability-list">{probabilities.map(([name, probability]) => <div className={name === move?.choice ? 'active' : ''} key={name}><span>{directionName(name)}</span><div><i style={{ width: `${probability * 100}%` }} /></div><b>{Math.round(probability * 100)}%</b></div>)}</div>{event.answer?.answers?.trap && <div className="inspector-subline">风险判断：{Math.round((event.answer.answers.trap.noul ?? 0) * 100)}% · {adjusted ? '触发安全路线' : '沿用模型选择'}</div>}</div><details className="raw-trace"><summary>查看原始请求 / 响应 JSON</summary><div className="trace-columns"><div><label>请求</label><pre>{JSON.stringify(event.request ?? event.state, null, 2)}</pre></div><div><label>响应</label><pre>{JSON.stringify(event.answer ?? { selected: event.selected }, null, 2)}</pre></div></div></details></div>}</article>;
}
