import { useEffect, useRef, useState } from 'react';
import { DecisionLab, useDecisionLab } from '../components/DecisionLab';

type Point = { x: number; y: number };
type Direction = 'up' | 'down' | 'left' | 'right';
type Snapshot = { grid: number; snake: Point[]; food: Point; direction: Direction; score: number; legalMoves: Direction[]; plannedDirection: Direction; loopDetected: boolean; recentHeads: Point[] };
const GRID = 20;
const DIRECTIONS: Record<Direction, Point> = { up: { x: 0, y: -1 }, down: { x: 0, y: 1 }, left: { x: -1, y: 0 }, right: { x: 1, y: 0 } };
const LABEL: Record<Direction, string> = { up: '上', down: '下', left: '左', right: '右' };
const opposite: Record<Direction, Direction> = { up: 'down', down: 'up', left: 'right', right: 'left' };
const legalMoves = (snake: Point[], direction: Direction) => (Object.keys(DIRECTIONS) as Direction[]).filter(name => { if (opposite[direction] === name) return false; const head = { x: snake[0].x + DIRECTIONS[name].x, y: snake[0].y + DIRECTIONS[name].y }; return head.x >= 0 && head.x < GRID && head.y >= 0 && head.y < GRID && !snake.some(part => part.x === head.x && part.y === head.y); });
function plannedRoute(snake: Point[], food: Point, direction: Direction): Direction { const allowed = new Set(legalMoves(snake, direction)); const blocked = new Set(snake.slice(0, -1).map(point => `${point.x},${point.y}`)); const queue: Array<{ point: Point; path: Direction[] }> = [{ point: snake[0], path: [] }]; const seen = new Set([`${snake[0].x},${snake[0].y}`]); while (queue.length) { const current = queue.shift()!; if (current.point.x === food.x && current.point.y === food.y) return current.path[0] ?? [...allowed][0] ?? direction; for (const [name, delta] of Object.entries(DIRECTIONS) as [Direction, Point][]) { if (!current.path.length && !allowed.has(name)) continue; const next = { x: current.point.x + delta.x, y: current.point.y + delta.y }; const id = `${next.x},${next.y}`; if (next.x < 0 || next.x >= GRID || next.y < 0 || next.y >= GRID || blocked.has(id) || seen.has(id)) continue; seen.add(id); queue.push({ point: next, path: [...current.path, name] }); } } return [...allowed][0] ?? direction; }
function draw(ctx: CanvasRenderingContext2D, snake: Point[], food: Point) { const cell = 600 / GRID; ctx.fillStyle = '#0d1719'; ctx.fillRect(0, 0, 600, 600); ctx.strokeStyle = 'rgba(106,242,210,.07)'; for (let i = 1; i < GRID; i++) { ctx.beginPath(); ctx.moveTo(i * cell, 0); ctx.lineTo(i * cell, 600); ctx.stroke(); ctx.beginPath(); ctx.moveTo(0, i * cell); ctx.lineTo(600, i * cell); ctx.stroke(); } ctx.save(); ctx.fillStyle = '#ff9b64'; ctx.shadowColor = '#ff9b64'; ctx.shadowBlur = 18; ctx.beginPath(); ctx.arc(food.x * cell + cell / 2, food.y * cell + cell / 2, cell * .28, 0, Math.PI * 2); ctx.fill(); ctx.restore(); snake.forEach((part, index) => { ctx.fillStyle = index === 0 ? '#b7ff4a' : '#5d9e54'; ctx.beginPath(); ctx.roundRect(part.x * cell + 3, part.y * cell + 3, cell - 6, cell - 6, 5); ctx.fill(); }); }

export default function SnakeGamePage() {
  const lab = useDecisionLab(); const canvasRef = useRef<HTMLCanvasElement>(null); const epoch = useRef(0); const stateRef = useRef<any>(null);
  const [snake, setSnake] = useState<Point[]>([{ x: 9, y: 10 }, { x: 8, y: 10 }, { x: 7, y: 10 }]); const [food, setFood] = useState<Point>({ x: 14, y: 10 }); const [direction, setDirection] = useState<Direction>('right'); const [queued, setQueued] = useState<Direction>('right'); const [score, setScore] = useState(0); const [best, setBest] = useState(() => Math.max(Number(localStorage.getItem('react-snake-best') || 0), Number(localStorage.getItem('gridloop-best') || 0))); const [combo, setCombo] = useState(0); const [loopBreaks, setLoopBreaks] = useState(0); const [recentHeads, setRecentHeads] = useState<Point[]>([]); const [running, setRunning] = useState(false); const [paused, setPaused] = useState(false); const [autopilot, setAutopilot] = useState(false); const [thinking, setThinking] = useState(false); const [confidence, setConfidence] = useState('等待'); const [message, setMessage] = useState('选择方向开始游戏，也可以让 Jev 自动驾驶。'); const [logs, setLogs] = useState<string[]>([]); const [trace, setTrace] = useState<unknown[]>([]);
  stateRef.current = { snake, food, direction, queued, score, combo, recentHeads, autopilot, loopBreaks, paused };
  const randomFood = (body: Point[]) => { const free: Point[] = []; for (let y = 0; y < GRID; y++) for (let x = 0; x < GRID; x++) if (!body.some(part => part.x === x && part.y === y)) free.push({ x, y }); return free[Math.floor(Math.random() * free.length)] ?? { x: 1, y: 1 }; };
  const move = (nextDirection: Direction) => { const current = stateRef.current; const delta = DIRECTIONS[nextDirection]; const head = { x: current.snake[0].x + delta.x, y: current.snake[0].y + delta.y }; if (head.x < 0 || head.x >= GRID || head.y < 0 || head.y >= GRID || current.snake.some((part: Point) => part.x === head.x && part.y === head.y)) { setRunning(false); setAutopilot(false); setMessage(`这一局撞到了边界或自己的身体，得分 ${current.score}。点击重置重新开始。`); return false; } const nextSnake = [head, ...current.snake]; let nextScore = current.score; let nextFood = current.food; let nextCombo = 0; let nextRecent = [...current.recentHeads, head].slice(-18); let nextBreaks = current.loopBreaks; if (head.x === current.food.x && head.y === current.food.y) { nextScore++; nextCombo = current.combo + 1; nextFood = randomFood(nextSnake); nextRecent = []; nextBreaks = 0; const nextBest = Math.max(best, nextScore); setBest(nextBest); localStorage.setItem('react-snake-best', String(nextBest)); localStorage.setItem('gridloop-best', String(nextBest)); } else nextSnake.pop(); setSnake(nextSnake); setFood(nextFood); setDirection(nextDirection); setScore(nextScore); setCombo(nextCombo); setRecentHeads(nextRecent); setLoopBreaks(nextBreaks); return true; };
  const saveTrace = (event: unknown) => setTrace(previous => { const next = [...previous, event]; localStorage.setItem('gridloop-live-trace', JSON.stringify(next)); fetch('/gridloop-api/trace', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(next) }).catch(() => {}); return next; });
  const aiStep = async () => { const current = stateRef.current; if (thinking || !current.autopilot || current.paused) return; setThinking(true); const currentEpoch = epoch.current; const planned = plannedRoute(current.snake, current.food, current.direction); const loopDetected = new Set(current.recentHeads.map((point: Point) => `${point.x},${point.y}`)).size <= 5 && current.recentHeads.length >= 8; const snapshot: Snapshot = { grid: GRID, snake: current.snake, food: current.food, direction: current.direction, score: current.score, legalMoves: legalMoves(current.snake, current.direction), plannedDirection: planned, loopDetected, recentHeads: current.recentHeads }; try { const answer = await lab.request('/gridloop-api/move', snapshot); if (currentEpoch !== epoch.current || !stateRef.current.autopilot || stateRef.current.paused) return; const choice = answer?.answers?.move?.choice as Direction; const candidates = legalMoves(current.snake, current.direction); if (!candidates.includes(choice)) throw new Error('Jev 返回了当前候选列表之外的方向'); const trapRisk = answer?.answers?.trap?.noul ?? 0; const distance = (name: Direction) => Math.abs(current.snake[0].x + DIRECTIONS[name].x - current.food.x) + Math.abs(current.snake[0].y + DIRECTIONS[name].y - current.food.y); const unsafe = loopDetected || trapRisk >= 0.6 || distance(choice) > distance(planned); const selected = unsafe ? planned : choice; lab.executed(selected, choice); setQueued(selected); setConfidence(`${Math.round((answer?.answers?.move?.confidence ?? 0) * 100)}%`); setMessage(unsafe ? `检测到风险，改用安全路线向${LABEL[selected]}。` : `Jev 选择向${LABEL[selected]}走，继续接近食物。`); setLogs(previous => [`${unsafe ? '系统调整' : 'Jev'} ${LABEL[selected]} · confidence ${Math.round((answer?.answers?.move?.confidence ?? 0) * 100)}%`, ...previous].slice(0, 6)); const nextBreaks = unsafe ? current.loopBreaks + 1 : 0; setLoopBreaks(nextBreaks); const executed = nextBreaks >= 2 ? planned : selected; if (nextBreaks >= 2) { setLoopBreaks(0); setMessage(`重复轨迹已打断，使用安全路线向${LABEL[planned]}脱困。`); } move(executed); saveTrace({ step: trace.length + 1, state: snapshot, answer, selected: executed, scoreAfter: current.score + (executed && current.snake[0].x + DIRECTIONS[executed].x === current.food.x && current.snake[0].y + DIRECTIONS[executed].y === current.food.y ? 1 : 0), timestamp: new Date().toISOString() }); } catch (error) { setAutopilot(false); setRunning(false); setMessage(error instanceof Error ? error.message : 'Jev 请求失败，自动驾驶已停止。'); } finally { setThinking(false); } };
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === ' ') { event.preventDefault(); if (running) setPaused(value => !value); else setRunning(true); return; } const map: Record<string, Direction> = { ArrowUp: 'up', w: 'up', ArrowDown: 'down', s: 'down', ArrowLeft: 'left', a: 'left', ArrowRight: 'right', d: 'right' }; const next = map[event.key]; if (!next || autopilot || opposite[next] === direction) return; setQueued(next); setRunning(true); setPaused(false); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, [autopilot, direction, running]);
  useEffect(() => { if (!running || paused || autopilot) return; const timer = window.setInterval(() => move(stateRef.current.queued), Math.max(90, 190 - Math.min(70, score * 5))); return () => window.clearInterval(timer); }, [running, paused, autopilot, score]);
  useEffect(() => { if (!autopilot || paused) return; let cancelled = false; let timer: number | undefined; const loop = async () => { if (cancelled) return; await aiStep(); if (!cancelled && stateRef.current.autopilot && !stateRef.current.paused) timer = window.setTimeout(loop, 100); }; loop(); return () => { cancelled = true; if (timer !== undefined) window.clearTimeout(timer); }; }, [autopilot, paused]);
  useEffect(() => { const ctx = canvasRef.current?.getContext('2d'); if (ctx) draw(ctx, snake, food); }, [snake, food]);
  const reset = () => { epoch.current++; lab.reset(); setSnake([{ x: 9, y: 10 }, { x: 8, y: 10 }, { x: 7, y: 10 }]); setFood({ x: 14, y: 10 }); setDirection('right'); setQueued('right'); setScore(0); setCombo(0); setLoopBreaks(0); setRecentHeads([]); setRunning(false); setPaused(false); setAutopilot(false); setThinking(false); setConfidence('等待'); setLogs([]); setTrace([]); localStorage.removeItem('gridloop-live-trace'); setMessage('选择方向开始游戏，也可以让 Jev 自动驾驶。'); };
  const startAuto = async () => { if (autopilot) { setAutopilot(false); setPaused(true); return; } try { const response = await fetch('/gridloop-api/status'); if (!response.ok) throw new Error('请先配置 Jev 服务'); setAutopilot(true); setRunning(true); setPaused(false); setMessage('Jev 正在读取棋盘并选择下一步。'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Jev 服务不可用'); } };
  const status = autopilot ? (paused ? 'JEV · PAUSED' : thinking ? 'JEV · THINKING' : 'JEV · DRIVING') : running ? (paused ? 'LOCAL · PAUSED' : 'LOCAL · PLAYING') : 'READY';
  return <section className="native-game live-lab"><div className="native-game-head"><div><p className="eyebrow">SNAKE / LIVE GAME</p><h1>看 Jev 如何走下一步</h1><p>观察候选方向、模型选择和实际执行。棋盘上的每一步，都能对照右侧记录。</p></div><span>{status}</span></div><div className="lab-strategy"><b>当前策略</b><span>提供当前棋盘、合法方向、近期轨迹、路径参考和风险判断；如果模型选择会形成循环，系统会记录并打断。</span></div><div className="native-game-layout"><article className="native-board-card"><div className="board-topline"><span>STANDARD GRID</span><span>BEST {String(best).padStart(3, '0')}</span></div><canvas ref={canvasRef} width={600} height={600} /><div className="native-actions"><button className="primary-button" onClick={() => { setRunning(true); setPaused(false); }}>开始游戏</button><button onClick={() => setPaused(value => !value)}>{paused ? '继续' : '暂停'}</button><button onClick={reset}>重置</button></div><div className="native-hint">方向键 / WASD 控制 · 空格开始/暂停 · Jev 自动驾驶会调用真实服务</div></article><aside className="native-side"><DecisionLab lab={lab} game="snake" paused={paused} /><div className="native-metrics"><b>{String(score).padStart(2, '0')}<small>得分</small></b><b>{String(snake.length).padStart(2, '0')}<small>长度</small></b><b>{String(Math.min(9, 1 + Math.floor(score / 5))).padStart(2, '0')}<small>速度</small></b></div><div className="native-metrics"><b>{String(combo).padStart(2, '0')}<small>连击</small></b><b>{String(loopBreaks).padStart(2, '0')}<small>打断循环</small></b><b>{confidence}<small>Jev 置信度</small></b></div><div className="native-driver"><div className="driver-topline"><strong>Jev 决策</strong><span>{confidence}</span></div><p>{message}</p><button onClick={startAuto}>{autopilot ? '停止 Jev 自动驾驶' : '让 Jev 来玩'}</button><div className="native-log">{logs.map((log, index) => <div key={`${log}-${index}`}>{log}</div>)}</div></div><div className="native-rules"><b>怎么玩</b><span>方向键 / WASD　控制蛇</span><span>吃到橙色信号点　得分并变长</span><span>Jev 会读取轨迹、避开碰撞并打断循环</span></div></aside></div></section>;
}
